# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: KeyboardKit
description: >-
  KeyboardKit helps you create custom keyboards for iOS and iPadOS, using Swift and SwiftUI. 

url: https://keyboardkit.com
email: info@keyboardkit.com

copyright_year: 2016-2026
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

bluesky_username: keyboardkit.bsky.social
github_username: KeyboardKit
mastodon_username: keyboardkit@techhub.social
twitter_username: keyboardkitsdk

assets: /assets/
header_image: /assets/icon/header.png

locales:
  count:      77
  flags:      🇺🇸 🇦🇱 🇦🇪 🇦🇪 🇦🇲 🇦🇿 🇧🇾 🇧🇩 🇧🇬 🇦🇩 🏳️ 🏳️ 🇭🇷 🇨🇿 🇩🇰 🇳🇱 🇧🇪 🇦🇺 🇨🇦 🇬🇧 🇺🇸 🇪🇪 🇫🇴 🇵🇭 🇫🇮 🇫🇷 🇨🇦 🇧🇪 🇨🇭 🇬🇪 🇩🇪 🇦🇹 🇨🇭 🇬🇷 🇺🇸 🇮🇱 🇭🇺 🇮🇸 🏳️ 🇮🇩 🇮🇪 🇮🇹 🇰🇿 🇹🇯 🇹🇯 🇹🇯 🇱🇻 🇱🇹 🇲🇰 🇲🇾 🇲🇹 🇲🇳 🏳️ 🇳🇴 🇳🇴 🇮🇷 🇵🇱 🇵🇹 🇧🇷 🇷🇴 🇷🇺 🇷🇸 🇷🇸 🇹🇯 🇸🇰 🇸🇮 🇪🇸 🇦🇷 🇲🇽 🇸🇪 🇰🇪 🇹🇷 🇺🇦 🇺🇿 🇻🇳 🏴󠁧󠁢󠁷󠁬󠁳󠁿

urls:
  email:      mailto:info@keyboardkit.com
  email-business-license: mailto:info@keyboardkit.com?subject=Business%License
  email-custom-terms: mailto:info@keyboardkit.com?subject=Custom%20Terms
  rss:        https://keyboardkit.com/feed.xml

  business:     /business
  faq:          /faq
  case-studies: /case-studies
  escrow:       /features/escrow
  terminology:  /faq#terminology

  appstore:   https://itunes.apple.com/app/keyboardkit/id1568444977
  blog:       /blog
  bluesky:    https://bsky.app/profile/keyboardkit.bsky.social
  calendar:   https://calendar.app.google/HyJeUXdRczwkp3Jh6
  docs:       https://docs.keyboardkit.com
  github:     https://github.com/KeyboardKit/KeyboardKit
  gumroad:    https://kankoda.gumroad.com/l/keyboardkitpro
  issues:     https://github.com/KeyboardKit/KeyboardKit/issues
  mastodon:   https://techhub.social/@keyboardkit
  newsletter: https://kankoda.gumroad.com/subscribe
  pricing:    /pricing
  reddit:     https://www.reddit.com/r/KeyboardKit
  twitter:    https://twitter.com/keyboardkitsdk

  swift:      https://www.swift.org
  swiftui:    https://developer.apple.com/xcode/swiftui/

google-analytics:
  measurement-id: G-XJ0HPZDSM3

header:
  title: KeyboardKit
  icon: /assets/icon/header.png
  pages:
    - pages/info/about.md
    - pages/blog.md
    - pages/features.md
    - pages/pro/pro.html
    - pages/pricing.md

footer:
  # Sections with links defined as "Title | url" strings.
  sections:
    - title: Site
      links:
        - Home | /
        - About | /about
        - App | /app
        - FAQ | /faq
        - Industries | /industries
        - Case Studies | /case-studies
    - title: SDK
      links:
        - Features | /features
        - KeyboardKit Pro | /pro
        - Pricing | /pricing
        - Business Licenses | /business-licenses
        - Terms & Conditions | /pro/terms
        - Privacy Policy | /privacy
    - title: News & Press
      links:
        - Blog | /blog
        - RSS | https://keyboardkit.com/feed.xml
        - Newsletter | https://kankoda.gumroad.com/subscribe
        - Press | /press
    - title: Code
      links:
        - GitHub | https://github.com/KeyboardKit/KeyboardKit
        - Get Started | /get-started
        - Binaries & dSYMs | https://github.com/KeyboardKit/KeyboardKit-Binaries
        - Documentation | /documentation
        - Issue Tracker | https://github.com/KeyboardKit/KeyboardKit/issues
    - title: Contact
      links:
        - Contact | /contact
        - Bluesky | https://bsky.app/profile/keyboardkit.bsky.social
        - Mastodon | https://techhub.social/@keyboardkit
        - Reddit | https://www.reddit.com/r/KeyboardKit
        - Schedule a call | https://calendar.app.google/HyJeUXdRczwkp3Jh6

collections_dir: collections

collections:
  case-studies:
    output: true
    permalink: /case-studies/:name
  features:
    output: true
    permalink: /features/:name
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include: [".well-known"]

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: page
      image: /assets/headers/keyboardkit.jpg
  -
    scope:
      path: "pages/pro"
    values:
      back-link:
        title: Pricing
        url: /pricing
  -
    scope:
      type: "case-studies"
    values:
      layout: page-sidebar
      back-link:
        title: Case studies
        url: /case-studies
  -
    scope:
      type: "features"
    values:
      layout: feature
      assets: /assets/features/
      back-link:
        title: Features
        url: /features
      side-menu-append:
        - title: Documentation

  -
    scope:
      type: "posts"
    values:
      layout: post
      author: danielsaidi
      image:  /assets/headers/blog.jpg
      back-link:
        title: Blog
        url: /blog

exclude:
  - Gemfile
  - Gemfile.lock
  - _docs/